### ISSUE TITLE
Setting the simulation duration does not work

### ISSUE THREAD

**Issue by yuanyimei** [AntonelloDN/df_envimet#1]
Hi @AntonelloDN ,

I am sorry to bother you again.I've set the simDuration as 30 hours,but when I run this simulation it can only calculate 24 hours.I've try many times,but it still can't be modified.Could you please tell me what caused this situation?Waitting for your reply.
![微信图片_20190311153626](https://user-images.githubusercontent.com/39336329/54108403-dc72ef80-4416-11e9-88b0-a6198b083160.jpg)
![微信图片_20190311153612](https://user-images.githubusercontent.com/39336329/54108432-f01e5600-4416-11e9-9743-ba0cd2581ef7.jpg)

Regards,
Yuanyimei

**Comment by AntonelloDN** [comment]
Hi @yuanyimei 

I have tried to replicate the issue unsuccessfully:

![image](https://user-images.githubusercontent.com/16763953/54164651-b58bdc00-445d-11e9-9314-5f662f9fd21f.png)

![image](https://user-images.githubusercontent.com/16763953/54164635-a0af4880-445d-11e9-8ae4-75ffab1cc769.png)

Could you give me more details about your workflow (Eg. settings part) and tell me when you downloaded envimet from envimet website? Do you use the basic version?

Thanks,
Antonello

**Comment by yuanyimei** [comment]
Hi @AntonelloDN ,

I'm using the envi-met V4.4.1,the basic version.I downloaded it about several days ago.The following is my GH workflow.
![1](https://user-images.githubusercontent.com/39336329/54186173-be27f500-44e5-11e9-9a91-fe3a7c84eba2.jpg)

Thanks,
yuanyimei

**Comment by AntonelloDN** [comment]
Hi @yuanyimei ,

Your issue is clear. There is an hidden control that set automatically the length of Simpleforcing lists as simulation hours input in the plugin. For example, the component "DFenvimetSimpleForceByEPW" extract only 24 hours, so simulation day will be set automatically to 24 indipendently what you write in simulationday input.
Anyway, I have to remove this logic because of recently changes in  ENVI_MET 4.4.1 that:
<ul>
<li>works only with Simpleforcing or Fullforcing</li>
<li>It is possible to run more than 24 hours of simulation with one day of Simpleforcing</li>
<li> I think it is not possible to set more than 24 values of Simpleforcing, it cause simulation error (TBV with ENVI_MET developers)</li>
</ul>

**I remove the hidden rule soon**. In the meantime, you can apply a workaround:
a) Open SIMX file generated by plugin with a text editor;
b) Find this:  \<simDuration>24\</simDuration>
c) Change in this way:  \<simDuration>30\</simDuration>


Thanks,
Antonello

**Comment by yuanyimei** [comment]
Hi @AntonelloDN ,

Get it！Thank you very much！

Thanks,
yuanyimei

**Comment by AntonelloDN** [comment]
@yuanyimei 
latest WIP version has solved it. you can download it.

**Comment by yuanyimei** [comment]
thank you very much！It helps a lot.




| |
袁一美
|
|
邮箱：yuanymarch@163.com
|

签名由 网易邮箱大师 定制

On 10/21/2019 02:35, Antonello Di Nunzio wrote:

@yuanyimei
latest WIP version has solved it. you can download it.
